### ISSUE TITLE
[Build Errors] Multiple unused methods.

### ISSUE THREAD

**Issue by xVoidByte** [absencelul/d2r-mh#2]
Firstly, thanks for the contribution.

Upon building the source code from the repo, I get several warnings of unused methods.
I am not familiar with Rust language but I've tried building using:
*[profile.release]
rustflags = ["-C", "warn=dead_code"]*

That actually did not even build at all as rustflags is required to be enabled at all times.
Upon injection, nothing gets revealed, am I doing something wrong?
I'd love to learn Rust in order to contribute to the project with additional functionalities.

Cheers in advance for the assistance.

**Comment by absencelul** [comment]
Tbh, this was done in 20 mins and will likely have bugs.

The warnings you're seeing are fine they just occur because of unused code.

You should be able to compile fine by doing cargo build and using some injector like gh or extreme injector. Once in game the map should be revealed for every level you enter.

I don't really plan to do much with this other than let the community leach off of it. I may accept PRs though.

**Comment by xVoidByte** [comment]
> Tbh, this was done in 20 mins and will likely have bugs.
> 
> The warnings you're seeing are fine they just occur because of unused code.
> 
> You should be able to compile fine by doing cargo build and using some injector like gh or extreme injector. Once in game the map should be revealed for every level you enter.
> 
> I don't really plan to do much with this other than let the community leach off of it. I may accept PRs though.

I compiled it successfully, yeah, I read in the documentation about unused code and modified it slightly for testing purposes and apparently it revealed the act fine, but that was only once heading out of town, heading to different waypoint or act reveals only certain small portions of area around the character and that's about it, I'll read through Rust documentation and see if I can contribute to it but I'm still learning coding, I also use GH injector (just as an additional information), cheers for the reply.
